@startuml dfd0

title Level 0 DFD - PNEUMO Website

actor User as User
boundary "PNEUMO Website" as Website
control "Prediction System" as PredictionSystem

User -> Website : Interacts with
Website -> PredictionSystem : Sends Image
PredictionSystem --> Website : Sends Prediction
Website --> User : Displays Result

@enduml