@startuml dfd0
title Level 0 DFD - Context Diagram

actor User as U
boundary Website as W
control Server as S
database Database as D

U --> W : Interacts with
W --> S : Sends HTTP requests
S --> D : Queries/Modifies data

@enduml
