@startuml dfd1

title Level 1 DFD - PNEUMO Website

actor User as User
boundary "PNEUMO Website" as Website
control "Upload Handler" as UploadHandler
control "Prediction System" as PredictionSystem
database "Image Database" as ImageDB

User -> Website : Interacts with
Website -> UploadHandler : Sends Image
UploadHandler -> PredictionSystem : For Prediction
PredictionSystem --> UploadHandler : Sends Result
UploadHandler -> Website : Result
Website -> User : Displays Result

@enduml
